submitit INFO (2025-02-04 08:59:35,439) - Starting with JobEnvironment(job_id=1339362, hostname=arbeitsrechner, local_rank=0(1), node=0(1), global_rank=0(1))
submitit INFO (2025-02-04 08:59:35,440) - Loading pickle: /home/s3811141/repos/OmniOpt/ax/runs/test_wronggoing_stuff/0/single_runs/1339362/1339362_submitted.pkl
Error at execution of your program: ./.tests/test_wronggoing_stuff.bin/bin/tensorflow_syntax_error. Exit-Code: 1, Signal-Code: None
No stdout
stderr: Traceback (most recent call last):
  File "/home/s3811141/repos/OmniOpt/ax/./.tests/test_wronggoing_stuff.bin/bin/tensorflow_syntax_error", line 3, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Parameters: {"program": "tensorflow_syntax_error"}
Debug-Infos: 
========
DEBUG INFOS START:
Program-Code: ./.tests/test_wronggoing_stuff.bin/bin/tensorflow_syntax_error
pwd: /home/s3811141/repos/OmniOpt/ax
File: ./.tests/test_wronggoing_stuff.bin/bin/tensorflow_syntax_error
UID: 1000
GID: 1000
Status-Change-Time: 1710134182.2937162
Size: 481 Bytes
Permissions: -rwxr-xr-x
Owner: s3811141
Last access: 1738651829.0453262
Last modification: 1710134182.2937162
Hostname: arbeitsrechner
========
DEBUG INFOS END

./.tests/test_wronggoing_stuff.bin/bin/tensorflow_syntax_error
stdout was empty
stderr: Traceback (most recent call last):
  File "/home/s3811141/repos/OmniOpt/ax/./.tests/test_wronggoing_stuff.bin/bin/tensorflow_syntax_error", line 3, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Result: None
EXIT_CODE: 1
submitit INFO (2025-02-04 08:59:38,591) - Job completed successfully
submitit INFO (2025-02-04 08:59:38,592) - Exiting after successful completion
