submitit INFO (2025-02-04 08:59:50,017) - Starting with JobEnvironment(job_id=1341453, hostname=arbeitsrechner, local_rank=0(1), node=0(1), global_rank=0(1))
submitit INFO (2025-02-04 08:59:50,017) - Loading pickle: /home/s3811141/repos/OmniOpt/ax/runs/test_wronggoing_stuff/0/single_runs/1341453/1341453_submitted.pkl
Error at execution of your program: ./.tests/test_wronggoing_stuff.bin/bin/module_not_found. Exit-Code: 1, Signal-Code: None
No stdout
stderr: Traceback (most recent call last):
  File "/home/s3811141/repos/OmniOpt/ax/./.tests/test_wronggoing_stuff.bin/bin/module_not_found", line 3, in <module>
    import THISMODULEDOESNTEXIST
ModuleNotFoundError: No module named 'THISMODULEDOESNTEXIST'

Parameters: {"program": "module_not_found"}
Debug-Infos: 
========
DEBUG INFOS START:
Program-Code: ./.tests/test_wronggoing_stuff.bin/bin/module_not_found
pwd: /home/s3811141/repos/OmniOpt/ax
File: ./.tests/test_wronggoing_stuff.bin/bin/module_not_found
UID: 1000
GID: 1000
Status-Change-Time: 1710134182.2937162
Size: 53 Bytes
Permissions: -rwxr-xr-x
Owner: s3811141
Last access: 1738651829.0453262
Last modification: 1710134182.2937162
Hostname: arbeitsrechner
========
DEBUG INFOS END

./.tests/test_wronggoing_stuff.bin/bin/module_not_found
stdout was empty
stderr: Traceback (most recent call last):
  File "/home/s3811141/repos/OmniOpt/ax/./.tests/test_wronggoing_stuff.bin/bin/module_not_found", line 3, in <module>
    import THISMODULEDOESNTEXIST
ModuleNotFoundError: No module named 'THISMODULEDOESNTEXIST'

Result: None
EXIT_CODE: 1
submitit INFO (2025-02-04 08:59:52,938) - Job completed successfully
submitit INFO (2025-02-04 08:59:52,938) - Exiting after successful completion
