
⚠ Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.evaluate) at 0x7fce983840e0>", line 31, in evaluate
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2378, in evaluate
    write_job_infos_csv(parameters, stdout, program_string_with_params, exit_code, _signal, result)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.write_job_infos_csv) at 0x7fce98384040>", line 161, in write_job_infos_csv
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2300, in write_job_infos_csv
    str(start_time),
        ^^^^^^^^^^
NameError: name 'start_time' is not defined

----------------------
You can check full logs with 'job.stderr(0)' and 'job.stdout(0)'or at paths:
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/1/single_runs/646821/646821_0_log.err
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/1/single_runs/646821/646821_0_log.out


⚠ Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.evaluate) at 0x7fce983840e0>", line 31, in evaluate
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2378, in evaluate
    write_job_infos_csv(parameters, stdout, program_string_with_params, exit_code, _signal, result)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.write_job_infos_csv) at 0x7fce98384040>", line 161, in write_job_infos_csv
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2300, in write_job_infos_csv
    str(start_time),
        ^^^^^^^^^^
NameError: name 'start_time' is not defined

----------------------
You can check full logs with 'job.stderr(0)' and 'job.stdout(0)'or at paths:
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/1/single_runs/647202/647202_0_log.err
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/1/single_runs/647202/647202_0_log.out


⚠ You pressed CTRL+C or got a signal. Optimization stopped.

Best result could not be determined

